version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aung123
      - POSTGRES_DB=nest
    networks:
      - aung
  test-db:
    image: postgres:13
    ports: 
      - 5435:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aung123
      - POSTGRES_DB=nest
    networks:
      - aung
networks:
  aung:
